name: Upload new artifact to S3
on:
  push:
    branches:
      - master
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          mkdir upload
          cp ./aws-s3-cloud-formation.yaml ./upload/aws-s3-cloud-formation.yaml
          echo ${{ secrets.AWS_KEY_ID }}

      - run: "ls -a"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python -m pip install boto3
        env:
          ACCESS_KEY: ${{ secrets.AWS_KEY_ID }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: python s3-upload.py
