name: Upload new artifact to S3
on:
  push:
    branches:
      - master
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY: ${{ secrets.AWS_KEY_ID }}
      SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET: ${{ secrets.AWS_BUCKET }}
    steps:
      - uses: actions/checkout@master
      - run: "ls -a"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python -m pip install boto3
      - run: python s3-upload.py
